import assert from 'node:assert/strict';
import {createParentChannel} from '../plasticity-asset-tool-app/src/hostMessaging.mjs';
const sent = [];
const parent = {postMessage(data, origin) {sent.push({data, origin});}};
let channel = createParentChannel(parent);
channel.send({type:'pat:ready'});
assert.equal(sent.at(-1).origin, '*');
assert.equal(channel.receive({source:parent, origin:'null', data:{type:'pat:shown'}}), true);
channel.send({type:'pat:prepare', id:'pick'});
assert.equal(sent.at(-1).origin, '*');
assert.equal(channel.receive({source:parent, origin:'null', data:{type:'pat:prepared',id:'pick',ready:true}}), true);
assert.equal(channel.receive({source:{}, origin:'https://other.example'}), false);
channel.send({type:'pat:show'});
assert.equal(sent.at(-1).origin, '*');
assert.equal(channel.receive({source:parent, origin:'https://cad.example'}), true);
channel.send({type:'pat:hide'});
assert.equal(sent.at(-1).origin, 'https://cad.example');
channel = createParentChannel(parent);
channel.send({type:'pat:ready'});
assert.equal(sent.at(-1).origin, '*');
console.log('Parent handshake and focus preparation messaging passed');
