import assert from 'node:assert/strict';
import * as THREE from '../plasticity-asset-tool-app/node_modules/three/build/three.module.js';
import {sceneFor} from '../plasticity-asset-tool-app/src/geometryScene.mjs';
import {meshBounds,presetBasePoint} from '../plasticity-asset-tool-app/src/previewBasePoint.mjs';
const mesh={parts:[{positions:[10,20,30,14,20,30,10,24,30],normals:[0,0,1,0,0,1,0,0,1],indices:[0,1,2],edges:[],edge_groups:[]}]};
const bounds=meshBounds(mesh);
assert.deepEqual(presetBasePoint(bounds,'world'),[0,0,0]);
assert.deepEqual(presetBasePoint(bounds,'center'),[12,22,30]);
const wire={parts:[{positions:[],edges:[-2,4,-8,6,10,12]}]};
assert.deepEqual(presetBasePoint(meshBounds(wire),'bottom'),[2,7,-8]);
const view=sceneFor(mesh);
view.scene.updateMatrixWorld(true);view.camera.updateMatrixWorld(true);
const original=new THREE.Vector3(11,21,30);
const world=view.model.localToWorld(original.clone());
const projected=world.clone().project(view.camera);
const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(projected.x,projected.y),view.camera);
const hit=ray.intersectObjects(view.model.children)[0];assert.ok(hit);
assert.ok(view.model.worldToLocal(hit.point.clone()).distanceTo(original)<1e-6,'Picking must undo preview centering and Z-up rotation');
view.camera.zoom=3;view.camera.updateProjectionMatrix();
const projectedZoom=world.clone().project(view.camera);ray.setFromCamera(new THREE.Vector2(projectedZoom.x,projectedZoom.y),view.camera);
assert.ok(view.model.worldToLocal(ray.intersectObjects(view.model.children)[0].point.clone()).distanceTo(original)<1e-6);
view.dispose();
console.log('Preview base point: world coordinates, Z-up presets and zoomed ray picking verified');
